# Generated by Django 5.2.12 on 2026-03-16 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call_queue', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='callqueue',
            new_name='call_queues_tenant__600372_idx',
            old_name='call_queues_tenant_id_status_idx',
        ),
        migrations.RenameIndex(
            model_name='callqueue',
            new_name='call_queues_tenant__293cf4_idx',
            old_name='call_queues_tenant_id_job_id_idx',
        ),
        migrations.RenameIndex(
            model_name='callqueueitem',
            new_name='call_queue__queue_i_a07c5d_idx',
            old_name='call_queue_items_queue_id_status_idx',
        ),
        migrations.RenameIndex(
            model_name='callqueueitem',
            new_name='call_queue__tenant__8c4f74_idx',
            old_name='call_queue_items_tenant_app_idx',
        ),
        migrations.RenameIndex(
            model_name='callqueueitem',
            new_name='call_queue__queue_i_38dbbb_idx',
            old_name='call_queue_items_queue_pos_idx',
        ),
        migrations.AlterField(
            model_name='callqueue',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Queue configuration: max_concurrent_calls, delay_between_calls_seconds, max_retries, call_window_start, call_window_end, timezone, auto_shortlist_threshold, auto_reject_threshold, filter_statuses.'),
        ),
    ]
