# Generated by Django 5.2.12 on 2026-03-15 20:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PipelineStage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("owner_user_id", models.UUIDField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255)),
                ("order", models.IntegerField(default=0)),
                ("color", models.CharField(default="#6366f1", max_length=7)),
                ("is_default", models.BooleanField(default=False)),
                ("is_terminal", models.BooleanField(default=False)),
                ("auto_action", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "pipeline_stages",
                "ordering": ["order"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "order"],
                        name="pipeline_st_tenant__a09a8d_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant_id", "slug"), name="unique_tenant_stage_slug"
                    )
                ],
            },
        ),
    ]
