# Generated by Django 5.2.12 on 2026-03-15 20:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("owner_user_id", models.UUIDField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                (
                    "department",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("location", models.CharField(blank=True, default="", max_length=255)),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("FULL_TIME", "Full Time"),
                            ("PART_TIME", "Part Time"),
                            ("CONTRACT", "Contract"),
                            ("INTERNSHIP", "Internship"),
                        ],
                        default="FULL_TIME",
                        max_length=20,
                    ),
                ),
                (
                    "experience_level",
                    models.CharField(
                        choices=[
                            ("ENTRY", "Entry"),
                            ("MID", "Mid"),
                            ("SENIOR", "Senior"),
                            ("LEAD", "Lead"),
                        ],
                        default="MID",
                        max_length=20,
                    ),
                ),
                (
                    "salary_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "salary_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("requirements", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("OPEN", "Open"),
                            ("PAUSED", "Paused"),
                            ("CLOSED", "Closed"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("application_count", models.IntegerField(default=0)),
                (
                    "voice_agent_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("voice_agent_config", models.JSONField(blank=True, default=dict)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("closes_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "jobs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "status"], name="jobs_tenant__a46df1_idx"
                    ),
                    models.Index(
                        fields=["tenant_id", "department"],
                        name="jobs_tenant__bacb62_idx",
                    ),
                ],
            },
        ),
    ]
