# Generated by Django 5.2.12 on 2026-03-15 20:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("owner_user_id", models.UUIDField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("actor_user_id", models.UUIDField(db_index=True)),
                (
                    "actor_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                (
                    "verb",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("updated", "Updated"),
                            ("deleted", "Deleted"),
                            ("status_changed", "Status Changed"),
                            ("published", "Published"),
                            ("closed", "Closed"),
                            ("triggered_call", "Triggered Call"),
                            ("call_completed", "Call Completed"),
                            ("call_failed", "Call Failed"),
                            ("interview_scheduled", "Interview Scheduled"),
                            ("interview_completed", "Interview Completed"),
                            ("interview_cancelled", "Interview Cancelled"),
                            ("scorecard_created", "Scorecard Created"),
                            ("note_added", "Note Added"),
                            ("bulk_action", "Bulk Action"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("resource_type", models.CharField(db_index=True, max_length=100)),
                ("resource_id", models.UUIDField(db_index=True)),
                (
                    "resource_label",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("before", models.JSONField(blank=True, null=True)),
                ("after", models.JSONField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "activities",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "resource_type", "resource_id"],
                        name="activities_tenant__d3f104_idx",
                    ),
                    models.Index(
                        fields=["tenant_id", "actor_user_id"],
                        name="activities_tenant__5e9e65_idx",
                    ),
                    models.Index(
                        fields=["tenant_id", "verb"],
                        name="activities_tenant__3239ac_idx",
                    ),
                    models.Index(
                        fields=["tenant_id", "created_at"],
                        name="activities_tenant__1ea538_idx",
                    ),
                ],
            },
        ),
    ]
