# Generated by Django 5.2.12 on 2026-03-15 20:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("applications", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Interview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("owner_user_id", models.UUIDField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "interview_type",
                    models.CharField(
                        choices=[
                            ("AI_VOICE", "AI Voice"),
                            ("HR_SCREEN", "HR Screen"),
                            ("TECHNICAL", "Technical"),
                            ("CULTURE_FIT", "Culture Fit"),
                            ("FINAL", "Final"),
                        ],
                        default="HR_SCREEN",
                        max_length=20,
                    ),
                ),
                ("scheduled_at", models.DateTimeField()),
                ("duration_minutes", models.IntegerField(default=30)),
                ("interviewer_user_id", models.UUIDField(blank=True, null=True)),
                (
                    "interviewer_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "interviewer_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("CONFIRMED", "Confirmed"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("NO_SHOW", "No Show"),
                        ],
                        default="SCHEDULED",
                        max_length=20,
                    ),
                ),
                ("meeting_link", models.URLField(blank=True, default="")),
                (
                    "calendar_event_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("feedback", models.TextField(blank=True, default="")),
                ("rating", models.IntegerField(blank=True, null=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interviews",
                        to="applications.application",
                    ),
                ),
            ],
            options={
                "db_table": "interviews",
                "ordering": ["-scheduled_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "scheduled_at"],
                        name="interviews_tenant__f2c1cc_idx",
                    ),
                    models.Index(
                        fields=["tenant_id", "status"],
                        name="interviews_tenant__be035f_idx",
                    ),
                    models.Index(
                        fields=["tenant_id", "interviewer_user_id"],
                        name="interviews_tenant__c43c65_idx",
                    ),
                ],
            },
        ),
    ]
