# Generated by Django 5.2.12 on 2026-03-15 20:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Applicant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("owner_user_id", models.UUIDField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, default="", max_length=20)),
                ("resume_url", models.URLField(blank=True, default="")),
                ("linkedin_url", models.URLField(blank=True, default="")),
                ("portfolio_url", models.URLField(blank=True, default="")),
                ("skills", models.JSONField(blank=True, default=list)),
                ("experience_years", models.IntegerField(blank=True, null=True)),
                (
                    "current_company",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "current_role",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("MANUAL", "Manual"),
                            ("WEBSITE", "Website"),
                            ("LINKEDIN", "LinkedIn"),
                            ("REFERRAL", "Referral"),
                            ("IMPORT", "Import"),
                        ],
                        default="MANUAL",
                        max_length=20,
                    ),
                ),
                ("tags", models.JSONField(blank=True, default=list)),
            ],
            options={
                "db_table": "applicants",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "email"],
                        name="applicants_tenant__07c813_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant_id", "email"),
                        name="unique_tenant_applicant_email",
                    )
                ],
            },
        ),
    ]
