# Generated by Django 5.2.12 on 2026-03-15 20:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("applications", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CallRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("owner_user_id", models.UUIDField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[("OMNIDIM", "Omnidim"), ("BOLNA", "Bolna")],
                        default="OMNIDIM",
                        max_length=20,
                    ),
                ),
                ("voice_agent_id", models.CharField(max_length=255)),
                (
                    "provider_call_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("phone", models.CharField(max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "Queued"),
                            ("INITIATED", "Initiated"),
                            ("RINGING", "Ringing"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("NO_ANSWER", "No Answer"),
                            ("BUSY", "Busy"),
                        ],
                        default="QUEUED",
                        max_length=20,
                    ),
                ),
                ("duration", models.IntegerField(blank=True, null=True)),
                ("transcript", models.TextField(blank=True, default="")),
                ("recording_url", models.URLField(blank=True, default="")),
                ("summary", models.TextField(blank=True, default="")),
                ("raw_response", models.JSONField(blank=True, default=dict)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, default="")),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="call_records",
                        to="applications.application",
                    ),
                ),
            ],
            options={
                "db_table": "call_records",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Scorecard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("owner_user_id", models.UUIDField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "communication_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=4),
                ),
                (
                    "knowledge_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=4),
                ),
                (
                    "confidence_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=4),
                ),
                (
                    "relevance_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=4),
                ),
                (
                    "overall_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=4),
                ),
                ("summary", models.TextField(blank=True, default="")),
                ("strengths", models.JSONField(blank=True, default=list)),
                ("weaknesses", models.JSONField(blank=True, default=list)),
                (
                    "recommendation",
                    models.CharField(
                        choices=[
                            ("STRONG_YES", "Strong Yes"),
                            ("YES", "Yes"),
                            ("MAYBE", "Maybe"),
                            ("NO", "No"),
                            ("STRONG_NO", "Strong No"),
                        ],
                        default="MAYBE",
                        max_length=20,
                    ),
                ),
                ("detailed_feedback", models.JSONField(blank=True, default=dict)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scorecards",
                        to="applications.application",
                    ),
                ),
                (
                    "call_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scorecard",
                        to="calls.callrecord",
                    ),
                ),
            ],
            options={
                "db_table": "scorecards",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="callrecord",
            index=models.Index(
                fields=["tenant_id", "application_id"],
                name="call_record_tenant__1e2096_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="callrecord",
            index=models.Index(
                fields=["tenant_id", "status"], name="call_record_tenant__f71b1a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="callrecord",
            index=models.Index(
                fields=["provider_call_id"], name="call_record_provide_dc6545_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scorecard",
            index=models.Index(
                fields=["tenant_id", "application_id"],
                name="scorecards_tenant__2414a7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="scorecard",
            index=models.Index(
                fields=["tenant_id", "overall_score"],
                name="scorecards_tenant__81a031_idx",
            ),
        ),
    ]
