# Generated by Django 5.2.12 on 2026-03-15 20:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("applicants", "0001_initial"),
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("owner_user_id", models.UUIDField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("APPLIED", "Applied"),
                            ("AI_SCREENING", "AI Screening"),
                            ("AI_COMPLETED", "AI Completed"),
                            ("SHORTLISTED", "Shortlisted"),
                            ("INTERVIEW_SCHEDULED", "Interview Scheduled"),
                            ("INTERVIEWED", "Interviewed"),
                            ("OFFER", "Offer"),
                            ("HIRED", "Hired"),
                            ("REJECTED", "Rejected"),
                            ("WITHDRAWN", "Withdrawn"),
                        ],
                        default="APPLIED",
                        max_length=30,
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("rejection_reason", models.TextField(blank=True, default="")),
                ("notes", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="applicants.applicant",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="jobs.job",
                    ),
                ),
            ],
            options={
                "db_table": "applications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "job_id", "status"],
                        name="application_tenant__7a784a_idx",
                    ),
                    models.Index(
                        fields=["tenant_id", "applicant_id"],
                        name="application_tenant__26d6eb_idx",
                    ),
                    models.Index(
                        fields=["tenant_id", "status"],
                        name="application_tenant__60b3ba_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant_id", "job_id", "applicant_id"),
                        name="unique_tenant_job_applicant",
                    )
                ],
            },
        ),
    ]
